import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { MobileNav } from "@/components/nav/MobileNav";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Header />
        {children}
        <div className="md:hidden fixed bottom-4 w-full">
          <MobileNav />
        </div>
      </body>
    </html>
  );
}
